// Mapeamento de nomes (PT-BR e EN) para códigos ISO
// Tudo em lowercase sem acento — normalizamos a entrada antes de comparar

export const TIME_PARA_ISO: Record<string, string> = {
  // === Times da Copa 2026 ===
  "brasil": "br",
  "brazil": "br",
  "africa do sul": "za",
  "south africa": "za",
  "marrocos": "ma",
  "morocco": "ma",
  "escocia": "gb-sct",
  "scotland": "gb-sct",
  "haiti": "ht",
  "mexico": "mx",
  "eua": "us",
  "estados unidos": "us",
  "united states": "us",
  "usa": "us",
  "canada": "ca",
  "coreia do sul": "kr",
  "south korea": "kr",
  "korea republic": "kr",
  "republic of korea": "kr",
  "republica tcheca": "cz",
  "tchequia": "cz",
  "czech republic": "cz",
  "czechia": "cz",
  "bosnia e herzegovina": "ba",
  "bosnia-herzegovina": "ba",
  "bosnia and herzegovina": "ba",
  "bosnia & herzegovina": "ba",
  "catar": "qa",
  "qatar": "qa",
  "suica": "ch",
  "switzerland": "ch",
  "paraguai": "py",
  "paraguay": "py",
  "australia": "au",
  "turquia": "tr",
  "turkey": "tr",
  "turkiye": "tr",
  "alemanha": "de",
  "germany": "de",
  "curacao": "cw",
  "costa do marfim": "ci",
  "ivory coast": "ci",
  "cote d'ivoire": "ci",
  "equador": "ec",
  "ecuador": "ec",
  "holanda": "nl",
  "paises baixos": "nl",
  "netherlands": "nl",
  "japao": "jp",
  "japan": "jp",
  "suecia": "se",
  "sweden": "se",
  "tunisia": "tn",
  "belgica": "be",
  "belgium": "be",
  "egito": "eg",
  "egypt": "eg",
  "ira": "ir",
  "iran": "ir",
  "nova zelandia": "nz",
  "new zealand": "nz",
  "espanha": "es",
  "spain": "es",
  "cabo verde": "cv",
  "ilhas de cabo verde": "cv",
  "cape verde": "cv",
  "cape verde islands": "cv",
  "arabia saudita": "sa",
  "saudi arabia": "sa",
  "uruguai": "uy",
  "uruguay": "uy",
  "franca": "fr",
  "france": "fr",
  "senegal": "sn",
  "iraque": "iq",
  "iraq": "iq",
  "noruega": "no",
  "norway": "no",
  "argentina": "ar",
  "argelia": "dz",
  "algeria": "dz",
  "austria": "at",
  "jordania": "jo",
  "jordan": "jo",
  "portugal": "pt",
  "rd congo": "cd",
  "republica democratica do congo": "cd",
  "congo dr": "cd",
  "dr congo": "cd",
  "democratic republic of the congo": "cd",
  "uzbequistao": "uz",
  "uzbekistan": "uz",
  "colombia": "co",
  "inglaterra": "gb-eng",
  "england": "gb-eng",
  "pais de gales": "gb-wls",
  "wales": "gb-wls",
  "croacia": "hr",
  "croatia": "hr",
  "gana": "gh",
  "ghana": "gh",
  "panama": "pa",
  "polonia": "pl",
  "poland": "pl",
  "dinamarca": "dk",
  "denmark": "dk",
  "italia": "it",
  "italy": "it",
  "russia": "ru",
  "ucrania": "ua",
  "ukraine": "ua",
  "chile": "cl",
  "peru": "pe",
  "venezuela": "ve",
  "camaroes": "cm",
  "cameroon": "cm",
  "nigeria": "ng",
};

function normalizar(nome: string): string {
  return nome
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // remove acentos
    .trim()
    .replace(/\s+/g, " ");
}

export function getBandeiraCircularUrl(time: string): string | null {
  if (!time) return null;
  const iso = TIME_PARA_ISO[normalizar(time)];
  if (!iso) return null;
  return `https://cdn.jsdelivr.net/gh/HatScripts/circle-flags/flags/${iso}.svg`;
}

// Mantém compat com código antigo
export function getBandeiraUrl(time: string): string | null {
  return getBandeiraCircularUrl(time);
}
